/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bold_it_discgroove_discgroove */

#ifndef _Included_com_bold_it_discgroove_discgroove
#define _Included_com_bold_it_discgroove_discgroove
#ifdef __cplusplus
extern "C" {
#endif
    
/*
 * Class:     com_bold_it_discgroove_discgroove
 * Method:    updateYaw
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_bold_1it_discgroove_discgroove_updateYaw
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
